/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movie_app;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

import static movie_app.movie.getMovies;



/**
 *
 * @author Antoine
 */
public class MoviesFrames extends javax.swing.JFrame {

    private Member aMember; //the member will be passed in the constructor of the next frame to keep the data
    private ArrayList<movie> theMovies; //the initial Arraylist, containings the basic getMovies() which returns all the movies
    private ArrayList<movie> theAvailableMovies= new ArrayList<movie>();//the second Arraylist which will be displayed on screen 
    private movie theChosenMovie;// the chosen movie will be passed in the constructor of the next frame
    DefaultListModel listModel= new DefaultListModel();
    
    /**
     * Creates new form MoviesFrames
     * @param theMember
     */
    
    public MoviesFrames(Member theMember) {
        initComponents();
        aMember= theMember;//Retrieves the user from previous page
        theMovies= getMovies();// Retrieves the list of movies on txt file
        for (int i=0; i<theMovies.size();i++){//Checks if the movie is available, from the initial Arraylist, and adds it to a second arraylist which will be displayed
            if (theMovies.get(i).isAvailability()==true){
                theAvailableMovies.add(theMovies.get(i));
            }
        }
        lblWelcome.setText("Welcome "+aMember.first_name+"!"); //Welcomes the user
        
        
        for (int i=0; i <theAvailableMovies.size(); i++){
            listModel.addElement(theAvailableMovies.get(i).getGenre()+"   ||    "+theAvailableMovies.get(i).getTitle());//adds the genre and title to the added element                          
                        
        }
        
        listMovies.setModel(listModel);
        
        if(aMember.getId()!=-1){
            btnPreviousBills.setVisible(true);
        }
        else{
            btnPreviousBills.setVisible(false);
        }
        
    }
    
    public MoviesFrames(){
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDisconnect = new javax.swing.JButton();
        btnGoToLogin = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMovies = new javax.swing.JList<>();
        btnChooseMovie = new javax.swing.JButton();
        lblWarning = new javax.swing.JLabel();
        btnPreviousBills = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDisconnect.setText("Disconnect");
        btnDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisconnectActionPerformed(evt);
            }
        });

        btnGoToLogin.setText("Login");
        btnGoToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToLoginActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblWelcome.setText("Welcome Guest!");

        jScrollPane1.setViewportView(listMovies);

        btnChooseMovie.setText("Choose a Movie!");
        btnChooseMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseMovieActionPerformed(evt);
            }
        });

        btnPreviousBills.setText("Previous Bills");
        btnPreviousBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousBillsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGoToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDisconnect)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChooseMovie)
                    .addComponent(btnPreviousBills, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDisconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPreviousBills, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnGoToLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChooseMovie, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToLoginActionPerformed
        // TODO add your handling code here:
        LoginFrame theLoginFrame= new LoginFrame(); //sends back to a login Frame
        theLoginFrame.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnGoToLoginActionPerformed

    private void btnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisconnectActionPerformed
        // TODO add your handling code here:
        MainFrame theMainFrame= new MainFrame(); //sends back to main menu
        theMainFrame.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnDisconnectActionPerformed

    private void btnChooseMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseMovieActionPerformed
        // TODO add your handling code here:
        if (!listMovies.isSelectionEmpty()){
            int index= listMovies.getSelectedIndex();
            theChosenMovie= theAvailableMovies.get(index);
            SelectedMovieFrame theMovieFrame = null;
            try {
                theMovieFrame = new SelectedMovieFrame(theChosenMovie,aMember);
            } catch (IOException ex) {
                Logger.getLogger(MoviesFrames.class.getName()).log(Level.SEVERE, null, ex);
            }
            theMovieFrame.setVisible(true);
            this.dispose();
        }
        else{
            lblWarning.setText("Please choose a movie!");
        }
    }//GEN-LAST:event_btnChooseMovieActionPerformed

    private void btnPreviousBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousBillsActionPerformed
        // TODO add your handling code here:
        PreviousBills billFrame= new PreviousBills(aMember);
        billFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPreviousBillsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoviesFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoviesFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoviesFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoviesFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoviesFrames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseMovie;
    private javax.swing.JButton btnDisconnect;
    private javax.swing.JButton btnGoToLogin;
    private javax.swing.JButton btnPreviousBills;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JList<String> listMovies;
    // End of variables declaration//GEN-END:variables
}
